### ISSUE TITLE
Releases with no download option throw errors

### ISSUE THREAD

**Issue by sixty4k** [sixty4k/bandcamp-collection-downloader#3]
There’s definitely ‘no valid download’ errors, but something’s not working for them.

Example:
```
Exception in thread "pool-1-thread-3" java.lang.NullPointerException
        at bandcampcollectiondownloader.BandcampAPIConnector.retrieveRealDownloadURL(BandcampAPIConnector.kt:177)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:133)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "pool-1-thread-5" java.lang.NullPointerException
        at bandcampcollectiondownloader.BandcampAPIConnector.retrieveRealDownloadURL(BandcampAPIConnector.kt:177)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.manageDownloadPage(BandcampCollectionDownloader.kt:133)
        at bandcampcollectiondownloader.BandcampCollectionDownloader.access$manageDownloadPage(BandcampCollectionDownloader.kt:13)
        at bandcampcollectiondownloader.BandcampCollectionDownloader$downloadAll$task$1.run(BandcampCollectionDownloader.kt:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by sixty4k** [comment]
Example of a no-download release: https://medicalrecords.bandcamp.com/album/helium-mr-052

**Comment by Ezwen** [comment]
Interesting! If you have time, can you open/copy this issue on the original repo?

**Comment by sixty4k** [comment]
Sure thing, this was mostly my notes to self as I tried to solve it.  :D
